title: "Incuboot"
icon-size: 94
window:
  size:
    width: 600
    height: 450
background: "../../../macos/packaging/assets/background.jpg"
contents:
  - x: 141
    y: 249
    type: "file"
    path: "Incuboot.app"
    name: "Incuboot.app"
  - x: 458
    y: 249
    type: "link"
    path: "/Applications"
